#dockerfile naif
# From python:3.14
# WORKDIR /app
# COPY . .
# RUN pip install uv && uv sync
# EXPOSE 8000
# CMD uv run fastapi run src/fleet_api/api.py --host 0.0.0.0 --port 8000

#dockerfile v1
# FROM python:3.14-slim-trixie
# WORKDIR /app
# COPY . .
# RUN pip install uv && uv sync
# EXPOSE 8000
# CMD uv run fastapi run src/fleet_api/api.py --host 0.0.0.0 --port 8000

#dockerfile v2
# FROM python:3.14-slim-trixie
# WORKDIR /app
# RUN pip install uv

# (1) carton n°1 : les dépendances seules (la couche lourde)
# COPY pyproject.toml uv.lock README.md ./
# RUN uv sync --locked --no-install-project

# (2) carton n°2 : le code, puis le projet lui-même
# COPY src ./src
# RUN uv sync --locked

# EXPOSE 8000
# CMD uv run fastapi run src/fleet_api/api.py --host 0.0.0.0 --port 8000

#dockerfile v3
# ===== Étage 1 : l'atelier =====
FROM python:3.14-slim-trixie AS builder
COPY --from=ghcr.io/astral-sh/uv:0.12.6 /uv /uvx /bin/
ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy \
    UV_PYTHON_DOWNLOADS=0 UV_NO_DEV=1
WORKDIR /app

COPY pyproject.toml uv.lock README.md ./
RUN uv sync --locked --no-install-project --no-editable

COPY src ./src
RUN uv sync --locked --no-editable

# ===== Étage 2 : la vitrine =====
FROM python:3.14-slim-trixie
WORKDIR /app
COPY --from=builder /app/.venv /app/.venv
COPY --from=builder /app/src /app/src
ENV PATH="/app/.venv/bin:$PATH"
EXPOSE 8000
CMD fastapi run src/fleet_api/api.py --host 0.0.0.0 --port 8000
