name: CI

on:    
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:                      

 #CAHCEAHACEAHE CACHE TEST HAHAHAHA
jobs:
  # on remet les uses a chaque fois car chaque job est isolé et n'a pas accès aux machines des autres jobs
  lint :
    runs-on: ubuntu-latest                # sur quelle machine : un Linux prêté par GitHub
    steps:
      - uses: actions/checkout@v7         # 1. récupérer le code
      - uses: astral-sh/setup-uv@v10.2.0  # 2. installer uv
        with:
          enable-cache: true
      - run: uv sync                      # 3. installer les dépendances
      - run: uv run ruff check .          # 4. check pour des erreurs de linting    
      - run: uv run ruff format --check . # 5. "dis-moi juste si un fichier devrait être reformaté, et échoue si c'est le cas"
  test:
    runs-on: ubuntu-latest                # sur quelle machine : un Linux prêté par GitHub
    steps:
      - uses: actions/checkout@v7         # 1. récupérer le code
      - uses: astral-sh/setup-uv@v10.2.0  # 2. installer uv
        with: 
          enable-cache: true
      - run: uv sync                      # 3. installer les dépendances
      - run: uv run pytest                # 4. lancer les tests
  build: 
    runs-on: ubuntu-latest                # sur quelle machine : un Linux prêté par GitHub
    steps:
      - uses: actions/checkout@v7         # 1. récupérer le code
      - uses: astral-sh/setup-uv@v10.2.0  # 2. installer uv
        with:
          enable-cache: true
      - run: uv sync                      # 3. installer les dépendances
      - run: uv build                     # 4. construire le package
